name: Docker Image CI for Kestra Trigger

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Print a message
        run: echo "${{ secrets.DOCKER_USERNAME }} || ${{ secrets.DOCKER_PASSWORD }}"

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        
        with:
          username: "VANIJ888"
          password: "Vani@20000602"

      - name: Build Docker image
        run: |
          docker build -f Dockerfile -t my-image-name-kestra:latest .

      - name: Tag Docker image
        run: |
          docker tag my-image-name-kestra:latest docker.io/VANIJ888/kestra-trigger:latest

      - name: Push Docker image
        run: |
          docker push docker.io/VANIJ888/kestra-trigger:latest